export default {
  SIGNUP_SUCCESSFUL: 1,
  SIGNUP_ERROR:      2,
  SIGNIN_SUCCESSFUL: 3,
  SIGNIN_ERROR:      4,
  TWEET_INDEX:       5,
  TWEET_CREATE:      6,
  TWEET_EDIT:        7,
  RECEIVED_LIKE:     8,
  DELETED_LIKE:      9,
  RECEIVED_COMMENT:  10,
  DELETED_COMMENT:   11,
};
