export default {
  SIGNUP_SUCCESSFUL: 1,
  SIGNUP_ERROR:      2,
  SIGNIN_SUCCESSFUL: 3,
  SIGNIN_ERROR:      4,
  TWEET_INDEX:       5,
  TWEET_CREATE:      6,
  TWEET_EDIT:        7,
  TWEET_UPDATE:      8,
  RECEIVED_LIKE:     9,
  DELETED_LIKE:      10,
  RECEIVED_COMMENT:  11,
  DELETED_COMMENT:   12,
};
