export default {
  SIGNUP_SUCCESSFUL: 1,
  SIGNUP_ERROR:      2,
  SIGNIN_SUCCESSFUL: 3,
  SIGNIN_ERROR:      4,
  RECEIVED_TWEETS:   5,
  RECEIVED_TWEET:    6,
  RECEIVED_LIKE:     7,
  DELETED_LIKE:      8,
  RECEIVED_COMMENT:  9,
  DELETED_COMMENT:   10,
};
